In [15]:
import numpy as np
a = np.array([[20,30,60],[50,10,40]])
b = np.array([[50,60,70],[60,70,90]])
print(a)
print(b)
print(a+b)
print(a*b)
print(np.add(a,b))
print(np.subtract(a,b))

[[20 30 60]
 [50 10 40]]
[[50 60 70]
 [60 70 90]]
[[ 70  90 130]
 [110  80 130]]
[[1000 1800 4200]
 [3000  700 3600]]
[[ 70  90 130]
 [110  80 130]]
[[-30 -30 -10]
 [-10 -60 -50]]


In [16]:
a = [[30,40,50],[60,70,80]]
arr = np.array(a)
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(type(arr))
print(arr.dtype)
print(arr.astype(float))
print(arr.astype(str))

(2, 3)
2
6
<class 'numpy.ndarray'>
int32
[[30. 40. 50.]
 [60. 70. 80.]]
[['30' '40' '50']
 ['60' '70' '80']]


In [18]:
a = np.array([2,3,6])
b = np.array([3])
print(np.power(a,b))

[  8  27 216]


In [19]:
a = np.array([4,9,16])
print(np.sqrt(a))

[2. 3. 4.]


In [21]:
a = np.array([20,30,60])
b = np.array([50,60,70])
print(np.concatenate([a,b]))

[20 30 60 50 60 70]


In [25]:
a = np.array([[20,30,60],[50,10,40]])
b = np.array([[50,60,70],[60,70,90]])
print(np.concatenate([a,b], axis = 1))
print(np.hstack([a,b]))        #horizontal concatenation
print(np.vstack([a,b]))        #vertical concatenation

[[20 30 60 50 60 70]
 [50 10 40 60 70 90]]
[[20 30 60 50 60 70]
 [50 10 40 60 70 90]]
[[20 30 60]
 [50 10 40]
 [50 60 70]
 [60 70 90]]


In [28]:
a = np.array([2,3,6,7,8,9])
b = np.array_split(a,3)
print(b)
print(b[1])

[array([2, 3]), array([6, 7]), array([8, 9])]
[6 7]


In [30]:
a = np.array([2,3,4])
print(np.append(a,5))
print(np.insert(a,1,50))

[2 3 4 5]
[ 2 50  3  4]


In [39]:
a = np.array([[2,3],[5,6]])
print(np.append(a,[8,9]))
print(np.insert(a,1,50))
print(np.insert(a,1,[50,60], axis = 0))

[2 3 5 6 8 9]
[ 2 50  3  5  6]
[[ 2  3]
 [50 60]
 [ 5  6]]


In [44]:
a = np.array([[2,3],[5,6]])
print(a)
print()
print(np.delete(a,1,axis = 0))

[[2 3]
 [5 6]]

[[2 3]]


In [3]:
import numpy as np
a = np.array([2,3,5,6])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

16
2
6
4
4.0
[ 2  5 10 16]
[  2   6  30 180]


In [11]:
price = np.array([100,150,199,200,250,130])
qunatity = np.array([10,50,30,40,30,10])
print(price,"\n",qunatity)
print()
c = np.cumprod([price,qunatity],axis = 0)
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

31270


In [19]:
import statistics as stats
food = np.array([100,150,199,150,250,130])
print(np.mean(food))
print(np.median(food))
print(stats.mode(food))
print(np.std(food))
print(np.var(food))

163.16666666666666
150.0
150
48.7524928137583
2376.805555555555


In [21]:
tobacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]
print(np.corrcoef([tobacco_consumption,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [24]:
prices = [300,100,350,150,200]
sales = [10,20,7,17,3]
print(np.corrcoef([prices,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
